import React from 'react'
import Navbar from '../Navbar/Navbar'
import { AnimatePresence, motion } from "framer-motion"

import { useState, useEffect } from 'react'
import Head from 'next/head'
import Footer from '../Footer/Footer'


const Layout = ({ children }: any) => {

  const [loading, setLoading] = useState(false);

  useEffect(() => {

    setTimeout(() => { setLoading(false) }, 3000);

  }, []);


  return (
    <AnimatePresence>
      {loading ?
        < motion.div
          key="screen"
          initial={{ opacity: 0, scale: 0 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={{ opacity: 0, x: 500 }}
          transition={{
            duration: 0.5,
            ease: "easeInOut"
          }}
          className=' flex justify-center items-center w-screen h-screen bg-primary overflow-hidden' >

          <motion.div
            key="box"
            animate={{
              scale: [1, 1.5, 1.5, 1],
              rotate: [0, 180, 360, 0],
              // borderRadius: ["20%", "20%", "20%", "20%"]
            }}
            transition={{
              duration: 1.5,
              ease: "easeInOut",
              times: [0, 0.3, 0.3, 0.9],
            }}

            className='  border-[5px] rounded-[60px]  border-sky-300 flex flex-col justify-center  items-center w-[400px] h-[400px]'>

            <motion.h1

              key="title"
              animate={{
                x: [-200, 0],
                scale: [0, 1]
              }}
              transition={{
                delay: 1.5,
                duration: 0.3,
                ease: "easeIn",
              }}

              className=' font-poppins text-white font-semibold text-7xl'>Inno
              <motion.span
                key="i"
                animate={{
                  y: [-50, 0],
                  scale: [0, 1]
                }}
                transition={{
                  delay: 1.8,
                  duration: 0.3,
                  ease: "easeIn",
                }}
                className=' text-rose-600 inline-block'>
                B
              </motion.span>
              ytes
            </motion.h1>

            <motion.span
              key="subtitle"
              animate={{
                x: [-200, 0],
                scale: [0, 1]
              }}
              transition={{
                delay: 1.5,
                duration: 0.3,
                ease: "easeIn",
              }}
              className=' font-dynapuff mt-6 text-white text-xl'>We deliver what is impossible</motion.span>
          </motion.div>

        </motion.div >
        :
        <>
          <Head>
            <title>InnoBytes</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/images/logo.png" />
          </Head>
          <div className='px-2 max:px-0 max-w-[1800px] m-auto relative overflow-hidden'>
            <Navbar />
            {children}
            <Footer />
          </div>
        </>
      }
    </AnimatePresence>
  );
}

export default Layout